Add equi_join mode to semi-join, and tests for it
Paradigm4/ArrayOpR pull request #27
Opened 2022-06-27 19:01 UTC by smoore-p4

semi-join 'auto' mode should use equi_join if semi_joining to more than one attribute/dimension
Fix version number in DESCRIPTION

2022-06-27 19:54 UTC, mpeterson-p4 requested changes
One small change in error messages needed, plus a couple questions - then this should be good to go assuming all the tests pass.

2022-06-27 19:54 UTC, mpeterson-p4 commented on R/array_op_base.R
> +        rand_id <- paste0(sample(c(0:9, LETTERS[1:6]), 6, T), collapse = '')
Not for this; But we should probably write a `create_random_id` method or something since this logic is used throughout.

2022-06-27 20:02 UTC, smoore-p4 commented on R/array_op_base.R
> +              "ERROR: ArrayOp$semi_join: cross_between mode: template must be a ArrayOp instance, but got: %s",
Good catch. a copy/paste error

2022-06-27 20:03 UTC, smoore-p4 commented on R/array_op_base.R
> +        rand_id <- paste0(sample(c(0:9, LETTERS[1:6]), 6, T), collapse = '')
We should, I figured I should try this out to see how it goes, BUT this would solve the multi-equi_join alias issue if we just bake it into the various joins if not specified.

2022-06-27 20:03 UTC, smoore-p4 commented on R/array_op_base.R
> +            #"cross_between"
Forgot to pull it out since equi-join now works.

2022-06-28 16:54 UTC, jwimberl commented on R/array_op_base.R
> +            "equi_join"
For this and the case below, would it maybe be good to auto-default to cross_between still when all the match columns are dimensions?

2022-06-28 20:21 UTC, smoore-p4 commented on R/array_op_base.R
> +            "equi_join"
It still doesn't work 'as expected' though... If you have only one dimension and ask for dim=1 and dim=10, semi_join in cross_between mode would give you all the entries 1 through 10, not just 1 and 10.
I don't like that it behaves differently than expected.

2022-06-28 20:21 UTC, smoore-p4 commented on R/array_op_base.R
> +            "equi_join"
(or... as I expect it to do :) )

2022-06-28 21:04 UTC, jwimberl commented on R/array_op_base.R
> +            "equi_join"
I find this works as you and I both expect:

```
X <- data.frame(value=letters)
Xarr <- conn$array_from_df(X)$persist(.gc=F)
Xarr$dims # look at this; was hiYV_ for me
Xarr$semi_join(data.frame(hiYV_=c(0,25)),mode="cross_betweeen")$to_df()
  value
1     a
2     z
```
The result is the same when adjusting upload_threshold to be more or less than the number of rows in the RHS data frame. Looking at the AFL created by the cross-between mode semi_join, it turns the 1-attribute data frame provided into a 2-attribute data frame with identical "low" and "high" columns, conforming to the cross_between operator requirements to select out single values.

2022-07-01 19:58 UTC, merged