Fix for arrow param
Paradigm4/ArrayOpR pull request #38
Opened 2023-02-15 21:04 UTC by mpeterson-p4

This PR makes the arrow parameters match the iquery params.

2023-02-15 21:11 UTC, jwimberl requested changes
Two required fixes regarding the `binary` parameter

2023-02-15 21:11 UTC, jwimberl commented on R/connection.R
> +        scidb::iquery(private$.db, afl_str, return = TRUE, only_attributes = only_attributes, arrow = use_arrow)
Another requirement is to add something like `binary = !use_arrow` to avoid the following:

```
> scidb::iquery(db, "list('operators')", return=TRUE, arrow=TRUE)
Error in scidb::iquery(db, "list('operators')", return = TRUE, arrow = TRUE) : 
  Only one of `binary` and `arrow` can be true
  ```

2023-02-15 21:11 UTC, jwimberl commented on R/connection.R
> +        scidb::iquery(private$.db, afl_str, return = FALSE, arrow = use_arrow)
Ditto here:

```
> scidb::iquery(db, "list('operators')", return=FALSE, arrow=TRUE)
Error in scidb::iquery(db, "list('operators')", return = FALSE, arrow = TRUE) : 
  Only one of `binary` and `arrow` can be true
  ```

2023-02-15 21:36 UTC, jwimberl approved these changes

2023-02-20 18:27 UTC, smoore-p4 approved these changes
Looks fine to me

2023-02-20 18:27 UTC, merged