Add apply_join mode to inner, left and semi joins
Paradigm4/ArrayOpR pull request #45
Opened 2023-12-05 18:07 UTC by jwimberl

* Adds apply_join mode to these three meta join modes
* Adds test cases, temporarily skipping the check that the semi-join output has the same schema as the reference due to https://github.com/Paradigm4/equi_join/issues/27

2023-12-05 18:32 UTC, jwimberl commented
The unit tests pass locally on a SciDB 23 machine with the exception of several failures related to SciDB data frames (issue #44) and datetime (issue #46)

2023-12-05 22:49 UTC, jwimberl commented
The unit tests also pass locally on a SciDB 19.11 machine, in which case there are no errors at all (issues #44 and #46 being specific to SciDB 23.10)

2023-12-11 18:24 UTC, smoore-p4 requested changes
Just the bits on the test using `$persist(.gc=False)` and/or add in the `$remove_array()` for them

2023-12-11 18:24 UTC, smoore-p4 commented on tests/testthat/test_join.R
> +  L = conn$array_from_df(leftDf, leftTemplate, force_template_schema = T)$change_schema(leftTemplate)$persist(.gc = F)
Is the `.gc = F` required here? I'm a little concerned about leaving arrays hanging around in general

2023-12-11 19:32 UTC, jwimberl commented on tests/testthat/test_join.R
> +  L = conn$array_from_df(leftDf, leftTemplate, force_template_schema = T)$change_schema(leftTemplate)$persist(.gc = F)
While the `.gc = F` may not be strictly necessary, persisting the array is required for some of the join cases to work. I've uncommented the `remove_array()` calls for this block in a new commit.

2023-12-11 19:33 UTC, jwimberl commented on tests/testthat/test_join.R
>    # L$remove_array()
Changed in a new commit

2023-12-12 16:14 UTC, smoore-p4 approved these changes

2023-12-12 16:14 UTC, merged